WebsiteTrangSuc/WebsiteTrangSuc/Models/Sanpham.cs
namespace WebsiteTrangSuc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Sanpham")]
    public partial class Sanpham
    {
        public int id { get; set; }
        [Display( Name="Mã sản phẩm")]
        [StringLength(30)]
        public string MaSanPham { get; set; }
        [Display(Name="ID Loại sản phẩm")]
        public int IdLoai { get; set; }
        [Display(Name ="Tên sản phẩm")]
        [StringLength(256)]
        public string Ten { get; set; }
        [Display(Name ="Model")]
        [StringLength(30)]
        public string Model { get; set; }
        [Display(Name ="Mô tả ngắn")]
        [StringLength(300)]
        public string MotaNgan { get; set; }
        [Display(Name ="Mô tả chi tiết")]
        [Column(TypeName = "ntext")]
        public string MotaChiTiet { get; set; }
        [Display(Name ="Thông số kỹ thuật")]
        [Column(TypeName = "ntext")]
        public string TSKyThuat { get; set; }
        [Display(Name ="Từ khóa")]
        [StringLength(300)]
        public string Tukhoa { get; set; }
        [Display(Name ="ID Hãng")]
        public int? IdHang { get; set; }
        [Display(Name ="Ngày nhập")]
        [Column(TypeName = "date")]
        public DateTime? NgayNhap { get; set; }
        [Display(Name ="Ngày cập nhập cuối")]
        [Column(TypeName = "date")]
        public DateTime? NgayCapNhatCuoi { get; set; }
        [Display(Name ="Giá cũ")]
        public double? GiaCu { get; set; }
        [Display(Name ="Giá mới")]
        public double? GiaMoi { get; set; }
        [Display(Name = "Ưu tiên")]
        public short? Uutien { get; set; }
        [Display(Name = "Thực thi")]
        public int? ThucThi { get; set; }
        [Display(Name = "Hình ảnh")]
        [StringLength(300)]
        public string HinhAnh { get; set; }
        [Display(Name = "Hình ảnh 1")]
        [StringLength(300)]
        public string HinhAnh1 { get; set; }
        [Display(Name = "Hình ảnh 2")]
        [StringLength(300)]
        public string HinhAnh3 { get; set; }
        [Display(Name = "Hình ảnh 3")]
        [StringLength(300)]
        public string HinhAnh4 { get; set; }
        [Display(Name = "Tiêu biểu")]
        public bool? TieuBieu { get; set; }
        [Display(Name = "Ngôn ngữ")]
        [StringLength(20)]
        public string Ngonngu { get; set; }

        public virtual LoaiSanPham LoaiSanPham { get; set; }
    }
}

WebsiteTrangSuc/WebsiteTrangSuc/Areas/Administrator/Controllers/SanphamsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebsiteTrangSuc.Models;

namespace WebsiteTrangSuc.Areas.Administrator.Controllers
{
    public class SanphamsController : Controller
    {
        private QLBH db = new QLBH();

        // GET: Administrator/Sanphams
        public ActionResult Index()
        {
            var sanphams = db.Sanphams.Include(s => s.LoaiSanPham);
            return View(sanphams.ToList());
        }

        // GET: Administrator/Sanphams/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sanpham sanpham = db.Sanphams.Find(id);
            if (sanpham == null)
            {
                return HttpNotFound();
            }
            return View(sanpham);
        }

        // GET: Administrator/Sanphams/Create
        public ActionResult Create()
        {
            ViewBag.IdLoai = new SelectList(db.LoaiSanPhams, "IdLoai", "Ten");
            return View();
        }

        // POST: Administrator/Sanphams/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create([Bind(Include = "id,MaSanPham,IdLoai,Ten,Model,MotaNgan,MotaChiTiet,TSKyThuat,Tukhoa,IdHang,NgayNhap,NgayCapNhatCuoi,GiaCu,GiaMoi,Uutien,ThucThi,HinhAnh,HinhAnh1,HinhAnh3,HinhAnh4,TieuBieu,Ngonngu")] Sanpham sanpham)
        {
            if (ModelState.IsValid)
            {
                db.Sanphams.Add(sanpham);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdLoai = new SelectList(db.LoaiSanPhams, "IdLoai", "Ten", sanpham.IdLoai);
            return View(sanpham);
        }

        // GET: Administrator/Sanphams/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sanpham sanpham = db.Sanphams.Find(id);
            if (sanpham == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdLoai = new SelectList(db.LoaiSanPhams, "IdLoai", "Ten", sanpham.IdLoai);
            return View(sanpham);
        }

        // POST: Administrator/Sanphams/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit([Bind(Include = "id,MaSanPham,IdLoai,Ten,Model,MotaNgan,MotaChiTiet,TSKyThuat,Tukhoa,IdHang,NgayNhap,NgayCapNhatCuoi,GiaCu,GiaMoi,Uutien,ThucThi,HinhAnh,HinhAnh1,HinhAnh3,HinhAnh4,TieuBieu,Ngonngu")] Sanpham sanpham)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sanpham).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdLoai = new SelectList(db.LoaiSanPhams, "IdLoai", "Ten", sanpham.IdLoai);
            return View(sanpham);
        }
        [HttpPost]
        // GET: Administrator/Sanphams/Delete/5
        public ActionResult Delete(int [] id)
        {
            foreach(var i in id)
            {
                Sanpham sp = db.Sanphams.Find(i);

                db.Sanphams.Remove(sp);
                db.SaveChanges();
            }
            return RedirectToAction("Index");

            
                //if (id == null)
            //{
            //    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            //}
            //Sanpham sanpham = db.Sanphams.Find(id);
            //if (sanpham == null)
            //{
            //    return HttpNotFound();
            //}
            //return View(sanpham);
        }

        // POST: Administrator/Sanphams/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    Sanpham sanpham = db.Sanphams.Find(id);
        //    db.Sanphams.Remove(sanpham);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult Close()
        {
            return RedirectToAction("Index", "Default");
        }
    }
}

WebsiteTrangSuc/WebsiteTrangSuc/Controllers/GioHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteTrangSuc.Models;

namespace WebsiteTrangSuc.Controllers
{
    public class GioHangController : Controller
    {
        // GET: GioHang
        const string cartname = "giohang";
        QLBH db = new QLBH();
        public ActionResult Index()
        {
            var giohang = (List<GioHang>)Session[cartname];
            return View(giohang);
        }
        public ActionResult ThemGioHang(int id)
        {
            var giohang = (List<GioHang>)Session[cartname];
            var sanpham = db.Sanphams.Find(id);
            if (giohang!=null)
            {
                if (giohang.Exists(x => x.Sanpham.id == id))
                {
                    var sp = giohang.Where(s => s.Sanpham.id == id).FirstOrDefault();
                    sp.SoLuong += sp.SoLuong;
                }
                else
                {
                    GioHang gh = new GioHang(sanpham, 1);
                    giohang.Add(gh);
                }
                Session[cartname] = giohang;
            }
            else
            {
                GioHang gh = new GioHang(sanpham, 1);
                var list = new List<GioHang>();
                list.Add(gh);
                Session[cartname] = list;
            }
            return Redirect(Request.UrlReferrer.ToString());
        }
        [HttpPost]
        public ActionResult TinhLai(int[] id, int[] soluong)
        {
            var k = 0;
            var giohang = (List<GioHang>)Session[cartname];
            foreach(int i in id)
            {
                if (giohang.Exists(s => s.Sanpham.id == i))
                {
                    var sp = giohang.Where(s => s.Sanpham.id == i).FirstOrDefault();
                    sp.SoLuong = soluong[k];
                }
                k++;
            }
            return RedirectToAction("Index");
        }
        public ActionResult ThanhToan()
        {
            if (Session["KH"] != null)
            {
                return RedirectToAction("DiaChi");
            }
            else
            {
                return View();
            }
           
        }
        [HttpPost]
        public ActionResult DangNhap(string txtTen, string txtMatKhau)
        {
            var kh = db.KhachHangs.Where(s => s.Tentruynhap == txtTen && s.Matkhau == txtMatKhau).ToList().FirstOrDefault();
            if (kh != null)
            {
                Session["KH"] = kh;
              
                return RedirectToAction("DiaChi");
            }
            else
            {
                Session["ms"] = "Đăng nhập không thành công";
                return RedirectToAction("ThanhToan");
            }
            
        }
        public ActionResult DangKy()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DangKy(string txtHoTen, string txtDienThoai,string txtDiaChi,string txtTenDangNhap,string txtMatKhau)
        {
            var khachhang = db.KhachHangs.Where(s => s.Tenkhachhang == txtHoTen).ToList().FirstOrDefault();
            if (khachhang!=null)
            {
                ViewBag.ms = "Tên đăng nhập đã tồn tại";
                return View();
            }
            else
            {
                KhachHang KH = new KhachHang();
                KH.Tentruynhap = txtTenDangNhap;
                KH.Tenkhachhang = txtHoTen;
                KH.Diachi = txtDiaChi;
                KH.Dienthoai = txtDienThoai;
                KH.Matkhau = txtMatKhau;
                db.KhachHangs.Add (KH);
                db.SaveChanges();
                Session["KH"] = KH;
                return RedirectToAction("DiaChi");
            }
            
        }
        public ActionResult DiaChi()
        {
            KhachHang khachhang = new KhachHang();
            khachhang = (KhachHang)Session["KH"];
            return View(khachhang);
        }
        [HttpPost]
        public ActionResult ThemDiaChi(string Tenkhachhang,string Dienthoai,string Diachi,string txtYeuCau,string txtNgayGiaoHang)
        {
            Donhang_KhachHang dh = new Donhang_KhachHang();
            KhachHang khachhang = new KhachHang();
            khachhang = (KhachHang)Session["KH"];
            dh.Idkhachhang = khachhang.IdKhachhang;
            dh.Tennguoinhan = Tenkhachhang;
            dh.Diachinguoinhan = Diachi;
            dh.DTnguoinhan = Dienthoai;
            dh.Yeucau = txtYeuCau;
            dh.Ngaygiao = Convert.ToDateTime(txtNgayGiaoHang);
            dh.Ngaydat = DateTime.Now;
            //db.Donhang_KhachHang.Add(dh);
            //db.SaveChanges();
            Session["dathang"] = dh;
            return RedirectToAction("DatHang");
        }
        public ActionResult DatHang()
        {
           ViewBag.kh = (KhachHang)Session["KH"];
           ViewBag.gh = (List<GioHang>)Session[cartname];
           ViewBag.dh = (Donhang_KhachHang)Session["dathang"];
            return View();
        }
        [HttpPost]

        public ActionResult DatHang(string rdphuongthuctt)
        {
           KhachHang kh = (KhachHang)Session["KH"];
            List <GioHang> gh = (List<GioHang>)Session[cartname];
            Donhang_KhachHang dh = (Donhang_KhachHang)Session["dathang"];
            dh.Kieuthanhtoan = rdphuongthuctt;
            db.Donhang_KhachHang.Add(dh);
            foreach(var item in gh)
            {
                Chitietdonhang chitiet = new Chitietdonhang();
                chitiet.IdDonHang = dh.IdDonHang;
                chitiet.IdSanPham = item.Sanpham.id;
                chitiet.Soluong = item.SoLuong;
                chitiet.Dongia = item.Sanpham.GiaMoi;
                db.Chitietdonhangs.Add(chitiet);
                db.SaveChanges();
                
            }
            
            return RedirectToAction("Dathangthanhcong");
        }
        public ActionResult Dathangthanhcong()
        {
            
            return View();
        }
    }
}

WebsiteTrangSuc/WebsiteTrangSuc/Controllers/SanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteTrangSuc.Models;

namespace WebsiteTrangSuc.Controllers
{
    public class SanPhamController : Controller
    {
        QLBH db = new QLBH();
        // GET: SanPham
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult SanPhamMoi()
        {
            var ds = db.Sanphams.OrderByDescending(s=>s.id).ToList().Take(3);
            return PartialView(ds);
        }
        public PartialViewResult SanPhamTieuBieu()
        {
            var ds = db.Sanphams.Where(s => s.TieuBieu == true).ToList().Take(2);
            return PartialView(ds);
        }
        [HttpGet]
        public ActionResult DanhMucSP(int id  )
        {
            var dssp = db.Sanphams.Where(s => s.IdLoai == id).OrderBy(s=>s.GiaMoi).ToList();
            ViewBag.tenloai = db.LoaiSanPhams.Where(s => s.IdLoai == id).ToList().FirstOrDefault();
            return View(dssp);
        }
        [HttpGet]
        public ActionResult Chitietsanpham(int id)
        {
            var chitiet = db.Sanphams.Where(s => s.id == id).ToList().FirstOrDefault();
            var splq = db.Sanphams.Where(s => s.IdLoai == chitiet.IdLoai && s.id != chitiet.id).ToList().Take(3);
            ViewBag.sqlq = splq;
            return View(chitiet);
        }
    }
}

WebsiteTrangSuc/WebsiteTrangSuc/Views/SanPham/Chitietsanpham.cshtml
@model WebsiteTrangSuc.Models.Sanpham
@using WebsiteTrangSuc.Models
@{
    ViewBag.Title = "Chitietsanpham";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<ul class="nav nav-tabs" style="padding-top:10px">
    <li role="presentation" class="active" style="border-color:#428bca"><a href="#" style="background-color:#428bca;color:#ffffff">Chi tiết sản phẩm</a></li>
</ul><p></p>
<link href="~/Content/Site.css" rel="stylesheet" />
<div class="row">
    <div class="col-sm-6 col-md-6">
        <div class="thumbnail hovergallery">
            <img src="@Model.HinhAnh" alt="...">
            <div class="caption">

            </div>
        </div>
    </div>
    <div class="col-sm-6 col-md-6">
        <div class="caption">
            <p>@Model.Ten</p>
            <p>- Mã sản phẩm : @Model.MaSanPham</p>
            <hr />
            
            <p class="gachgia">- Giá cũ : @Model.GiaCu ₫</p>
            <h4 style="color:#ff0000">- Giá mới : @Model.GiaMoi ₫</h4>
           <p>@Html.ActionLink("Đặt Mua", "ThemGioHang", "GioHang", new { id = Model.id }, new { @class = "btn btn-success", @role = "button" })</p>
        </div>
    </div>
</div>
<div>
    <ul class="nav nav-tabs" style="padding-top:10px">
        <li role="presentation" class="active" style="border-color:#428bca"><a href="#" style="background-color:#428bca;color:#ffffff">Mô tả sản phẩm</a></li>
    </ul>
   <p>@Html.Raw(Model.MotaChiTiet)
</p> 
</div>
<div>
    <ul class="nav nav-tabs" style="padding-top:10px">
        <li role="presentation" class="active" style="border-color:#428bca"><a href="#" style="background-color:#428bca;color:#ffffff">Sản phẩm liên quan</a></li>
    </ul>
    <div class="row">
        @{
            foreach (Sanpham item in ViewBag.sqlq)
            {
                <div class="col-sm-6 col-md-4">
                    <div class="thumbnail hovergallery">
                        <img src="@item.HinhAnh" alt="...">
                        <div class="caption">
                            <p>@Html.ActionLink(item.Ten, "Chitietsanpham", "SanPham", new { id = item.id }, null)</p>
                            <p class="gachgia">@item.GiaCu ₫</p>
                            <h4 style="color:#ff0000">@item.GiaMoi ₫</h4>
                            <p>
                                @*@Html.ActionLink("Chi tiết", "Chitietsanpham", "SanPham", new { id = item.id }, new { @class = "btn btn-default", @role = "button" })*@
                                @Html.ActionLink("Đặt Mua", "", "SanPham", new { id = item.id }, new { @class = "btn btn-success", @role = "button" })
                            </p>
                        </div>
                    </div>
                </div>
            }

        }
    </div>
    </div>




WebsiteTrangSuc/WebsiteTrangSuc/Views/SanPham/DanhMucSP.cshtml
@model IEnumerable<WebsiteTrangSuc.Models.Sanpham>
@{
    ViewBag.Title = "DanhMucSP";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/Site.css" rel="stylesheet" />
<ul class="nav nav-tabs" style="padding-top:10px">
    <li role="presentation" class="active" style="border-color:#428bca"><a href="#" style="background-color:#428bca;color:#ffffff">@ViewBag.tenloai.Ten</a></li>
</ul><p></p>
<div class="row">
    @{
        foreach(var item in Model)
        {
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail hovergallery">
                    <img src="@item.HinhAnh" alt="...">
                    <div class="caption">
                        <p>@Html.ActionLink(item.Ten, "Chitietsanpham", "SanPham", new { id = item.id }, null)</p>
                        <p class="gachgia">@item.GiaCu ₫</p>
                        <h4 style="color:#ff0000">@item.GiaMoi ₫</h4>
                        <p>
                            @*@Html.ActionLink("Chi tiết", "Chitietsanpham", "SanPham", new { id = item.id }, new { @class = "btn btn-default", @role = "button" })*@
                            @Html.ActionLink("Đặt Mua", "ThemGioHang", "GioHang", new { id = item.id }, new { @class = "btn btn-success", @role = "button" })
                        </p>
                    </div>
                </div>
            </div>
        }

    }

</div>

WebsiteTrangSuc/WebsiteTrangSuc/Views/SanPham/SanPhamMoi.cshtml
@model IEnumerable<WebsiteTrangSuc.Models.Sanpham>
<ul class="nav nav-tabs" style="padding-top:10px">
    <li role="presentation" class="active" style="border-color:#428bca" ><a href="#"style="background-color:#428bca;color:#ffffff">Sản phẩm mới <img src="~/Media/Image/18035712_1443198155701311_384693474_n.gif" /></a></li>
    </ul><p></p>
    <div class="row">
        @{
            foreach (var item in Model)
            {
                <div class="col-sm-6 col-md-4">
                    <div class="thumbnail">
                        <div class="hovergallery">
                            <img src="@item.HinhAnh" alt="..." height="200" width="200">
                        </div>
                        
                        <div class="caption">
                            <p>@Html.ActionLink(item.Ten,"Chitietsanpham","SanPham", new {id= item.id },null)</p>
                            <p class="gachgia"> @item.GiaCu ₫</p>
                            <h4 style="color:#ff0000"> @item.GiaMoi ₫</h4>
                            <p>
                                @*@Html.ActionLink("Chi tiết", "Chitietsanpham", "SanPham", new { id = item.id }, new { @class = "btn btn-default", @role = "button" })*@
                                @Html.ActionLink("Đặt Mua", "ThemGioHang", "GioHang", new { id = item.id }, new { @class = "btn btn-success", @role = "button" })
                            </p>
                        </div>
                    </div>
                </div>
            }

        }

    </div>
 

WebsiteTrangSuc/WebsiteTrangSuc/Views/SanPham/SanPhamTieuBieu.cshtml
@model IEnumerable<WebsiteTrangSuc.Models.Sanpham>
    @{
        foreach (var item in Model)
        {
            <div>
                <div class="thumbnail hovergallery ">
                    <img src="@item.HinhAnh" alt="..." width="200" height="200">
                    <div class="caption">
                        <p>@Html.ActionLink(item.Ten, "Chitietsanpham", "SanPham", new { id = item.id },null)</p>

                        <p class="gachgia"> @item.GiaCu ₫</p>
                        <h4 style="color:#ff0000"> @item.GiaMoi ₫</h4>
                        <p>
                            @*@Html.ActionLink("Chi tiết", "Chitietsanpham", "SanPham", new { id = item.id }, new { @class = "btn btn-default", @role = "button" })*@
                            @Html.ActionLink("Đặt Mua", "ThemGioHang", "GioHang", new { id = item.id }, new { @class = "btn btn-success", @role = "button" })
                        </p>
                    </div>
                </div>
            </div>
        }
    }